
/*
* Connections.
*/

// Fetch.
export const FETCH_CONNECTIONS = 'FETCH_CONNECTIONS';
export const FETCH_CONNECTIONS_PENDING = 'FETCH_CONNECTIONS_PENDING';
export const FETCH_CONNECTIONS_REJECTED = 'FETCH_CONNECTIONS_REJECTED';
export const FETCH_CONNECTIONS_FULFILLED = 'FETCH_CONNECTIONS_FULFILLED';

/*
* History.
*/

// Fetch.
export const FETCH_JOBS_LIST = 'FETCH_JOBS_LIST';
export const FETCH_JOBS_LIST_PENDING = 'FETCH_JOBS_LIST_PENDING';
export const FETCH_JOBS_LIST_REJECTED = 'FETCH_JOBS_LIST_REJECTED';
export const FETCH_JOBS_LIST_FULFILLED = 'FETCH_JOBS_LIST_FULFILLED';

// Check Status.
export const CHECK_JOB_STATUS = 'CHECK_JOB_STATUS';
export const CHECK_JOB_STATUS_PENDING = 'CHECK_JOB_STATUS_PENDING';
export const CHECK_JOB_STATUS_REJECTED = 'CHECK_JOB_STATUS_REJECTED';
export const CHECK_JOB_STATUS_FULFILLED = 'CHECK_JOB_STATUS_FULFILLED';

/*
* Columns.
*/
export const ADD_COLUMN = 'ADD_COLUMN';
export const REMOVE_COLUMN = 'REMOVE_COLUMN';

/*
 * Settings.
 */
export const UPDATE_SETTINGS = 'UPDATE_SETTINGS';
export const UPDATE_SEARCH_FILTER = 'UPDATE_SEARCH_FILTER';

/*
* Users.
*/

// Count.
export const FETCH_USER_COUNT = 'FETCH_USER_COUNT';
export const FETCH_USER_COUNT_PENDING = 'FETCH_USER_COUNT_PENDING';
export const FETCH_USER_COUNT_REJECTED = 'FETCH_USER_COUNT_REJECTED';
export const FETCH_USER_COUNT_FULFILLED = 'FETCH_USER_COUNT_FULFILLED';

/*
* Export.
*/

export const EXPORT_USERS_STARTED = 'EXPORT_USERS_STARTED';
export const EXPORT_USERS_COMPLETE = 'EXPORT_USERS_COMPLETE';
export const EXPORT_USERS_CANCEL = 'EXPORT_USERS_CANCEL';
export const EXPORT_USERS_PROGRESS = 'EXPORT_USERS_PROGRESS';
export const EXPORT_USERS_REJECTED = 'EXPORT_USERS_REJECTED';
export const EXPORT_DOWNLOAD = 'EXPORT_DOWNLOAD';
export const EXPORT_DOWNLOAD_PENDING = 'EXPORT_DOWNLOAD_PENDING';
export const EXPORT_DOWNLOAD_REJECTED = 'EXPORT_DOWNLOAD_REJECTED';
export const EXPORT_DOWNLOAD_FULFILLED = 'EXPORT_DOWNLOAD_FULFILLED';

export const SAVE_USERS_REJECTED = 'SAVE_USERS_REJECTED';
export const CLOSE_EXPORT_DIALOG = 'CLOSE_EXPORT_DIALOG';

// Token.
export const LOADED_TOKEN = 'LOADED_TOKEN';
export const RECIEVED_TOKEN = 'RECIEVED_TOKEN';

// Login.
export const SHOW_LOGIN = 'SHOW_LOGIN';
export const REDIRECT_LOGIN = 'REDIRECT_LOGIN';
export const LOGIN_PENDING = 'LOGIN_PENDING';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

// Logout.
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

/*
 * Import.
 */
export const IMPORT_USERS_PENDING = 'IMPORT_USERS_PENDING';
export const IMPORT_USERS_REJECTED = 'IMPORT_USERS_REJECTED';
export const IMPORT_USERS_FULFILLED = 'IMPORT_USERS_FULFILLED';
export const CANCEL_IMPORT = 'CANCEL_IMPORT';
export const CLEAR_IMPORT = 'CLEAR_IMPORT';
export const DROPPED_FILES = 'DROPPED_FILES';
export const PROBE_IMPORT_STATUS = 'PROBE_IMPORT_STATUS';
export const PROBE_IMPORT_STATUS_PENDING = 'PROBE_IMPORT_STATUS_PENDING';
export const PROBE_IMPORT_STATUS_REJECTED = 'PROBE_IMPORT_STATUS_REJECTED';
export const PROBE_IMPORT_STATUS_FULFILLED = 'PROBE_IMPORT_STATUS_FULFILLED';
export const IMPORT_USERS = 'IMPORT_USERS';
export const IMPORT_USERS_VALIDATION_FAILED = 'IMPORT_USERS_VALIDATION_FAILED';
export const REMOVE_FILE = 'REMOVE_FILE';
export const FORM_VALIDATION_FAILED = 'FORM_VALIDATION_FAILED';
export const DISMISS_ERROR = 'DISMISS_ERROR';
export const SET_CURRENT_JOB = 'SET_CURRENT_JOB';

/*
 * Report.
 */
export const GET_JOB_REPORT = 'GET_JOB_REPORT';
export const GET_JOB_REPORT_PENDING = 'GET_JOB_REPORT_PENDING';
export const GET_JOB_REPORT_REJECTED = 'GET_JOB_REPORT_REJECTED';
export const GET_JOB_REPORT_FULFILLED = 'GET_JOB_REPORT_FULFILLED';
export const SHOW_JOB_REPORT = 'SHOW_JOB_REPORT';
export const HIDE_JOB_REPORT = 'HIDE_JOB_REPORT';
