/*
 * Connections.
 */

// Fetch.
export const FETCH_CONNECTIONS = 'FETCH_CONNECTIONS';
export const FETCH_CONNECTIONS_PENDING = 'FETCH_CONNECTIONS_PENDING';
export const FETCH_CONNECTIONS_REJECTED = 'FETCH_CONNECTIONS_REJECTED';
export const FETCH_CONNECTIONS_FULFILLED = 'FETCH_CONNECTIONS_FULFILLED';

/*
 * Columns.
 */
export const ADD_COLUMN = 'ADD_COLUMN';

/*
 * Users.
 */

 // Count.
 export const FETCH_USER_COUNT = 'FETCH_USER_COUNT';
 export const FETCH_USER_COUNT_PENDING = 'FETCH_USER_COUNT_PENDING';
 export const FETCH_USER_COUNT_REJECTED = 'FETCH_USER_COUNT_REJECTED';
 export const FETCH_USER_COUNT_FULFILLED = 'FETCH_USER_COUNT_FULFILLED';
