/*
* Connections.
*/

// Fetch.
export const FETCH_CONNECTIONS = 'FETCH_CONNECTIONS';
export const FETCH_CONNECTIONS_PENDING = 'FETCH_CONNECTIONS_PENDING';
export const FETCH_CONNECTIONS_REJECTED = 'FETCH_CONNECTIONS_REJECTED';
export const FETCH_CONNECTIONS_FULFILLED = 'FETCH_CONNECTIONS_FULFILLED';

/*
* Columns.
*/
export const ADD_COLUMN = 'ADD_COLUMN';
export const REMOVE_COLUMN = 'REMOVE_COLUMN';

/*
 * Settings.
 */
export const UPDATE_SETTINGS = 'UPDATE_SETTINGS';
export const UPDATE_SEARCH_FILTER = 'UPDATE_SEARCH_FILTER';

/*
* Users.
*/

// Count.
export const FETCH_USER_COUNT = 'FETCH_USER_COUNT';
export const FETCH_USER_COUNT_PENDING = 'FETCH_USER_COUNT_PENDING';
export const FETCH_USER_COUNT_REJECTED = 'FETCH_USER_COUNT_REJECTED';
export const FETCH_USER_COUNT_FULFILLED = 'FETCH_USER_COUNT_FULFILLED';

/*
* Export.
*/

export const EXPORT_USERS_STARTED = 'EXPORT_USERS_STARTED';
export const EXPORT_USERS_COMPLETE = 'EXPORT_USERS_COMPLETE';
export const EXPORT_USERS_CANCEL = 'EXPORT_USERS_CANCEL';
export const EXPORT_USERS_PROGRESS = 'EXPORT_USERS_PROGRESS';
export const EXPORT_USERS_REJECTED = 'EXPORT_USERS_REJECTED';

export const SAVE_USERS_REJECTED = 'SAVE_USERS_REJECTED';
export const CLOSE_EXPORT_DIALOG = 'CLOSE_EXPORT_DIALOG';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
